[build]
builder = "NIXPACKS"
buildCommand = "npm install --legacy-peer-deps && npx prisma generate"

[deploy]
startCommand = "npx prisma migrate deploy && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[environments.production]
[environments.production.deploy]
startCommand = "npx prisma migrate deploy && npm start"

[environments.staging]
[environments.staging.deploy]
startCommand = "npx prisma migrate deploy && npm run dev"
